spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: ${DATABASE_URL} # jdbc:postgresql://localhost:5432/your_database
    username: ${DATABASE_USERNAME} # postgres
    password: ${DATABASE_PASSWORD} # postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
